// ─────────────────────────────────────────────────────────────────────────────
// Solar 4 All — Incentives Database
// Real programs by state and county. Data current as of 2024.
// ─────────────────────────────────────────────────────────────────────────────

export interface Incentive {
  name: string;
  type: 'tax_credit' | 'rebate' | 'net_metering' | 'exemption' | 'program';
  scope: 'federal' | 'state' | 'county' | 'utility';
  description: string;
  estimatedValue: string; // plain text, e.g. "30% of system cost"
  eligibility: string;
  link?: string;
}

// ─── Federal ──────────────────────────────────────────────────────────────────

const FEDERAL_INCENTIVES: Incentive[] = [
  {
    name: 'Residential Clean Energy Credit',
    type: 'tax_credit',
    scope: 'federal',
    description:
      'A federal income tax credit covering 30% of your total solar system cost, including installation. No cap on system size. Applies to panels, inverters, wiring, and labor.',
    estimatedValue: '30% of total system cost',
    eligibility:
      'Homeowners who owe federal income taxes. Primary or secondary residences. Credit is nonrefundable — you must owe taxes to use it. Available through 2032 at 30%, then steps down.',
    link: 'https://www.irs.gov/credits-deductions/residential-clean-energy-credit',
  },
];

// ─── Illinois ─────────────────────────────────────────────────────────────────

const IL_INCENTIVES: Incentive[] = [
  {
    name: 'Illinois Shines (Adjustable Block Program)',
    type: 'program',
    scope: 'state',
    description:
      'Illinois\'s main solar incentive — you sell Renewable Energy Credits (RECs) generated by your system over 15 years. Payments come upfront or over time through an approved vendor.',
    estimatedValue: '~$60–90/MWh over 15 years (~$3,000–8,000 for a typical home system)',
    eligibility:
      'ComEd and Ameren Illinois customers. System must be installed by an approved vendor. Applies to systems under 10 kW (residential) and larger commercial projects.',
    link: 'https://illinoisshines.com',
  },
  {
    name: 'Illinois Solar For All (ILSFA)',
    type: 'program',
    scope: 'state',
    description:
      'A program specifically for low- and moderate-income households. Approved vendors cover most or all of the system cost — you just sign a long-term subscription and pay nothing upfront.',
    estimatedValue: 'Up to 100% system cost covered, plus ongoing bill savings',
    eligibility:
      'Households at or below 80% of Area Median Income (AMI). Must use an ILSFA-approved vendor. Renters may qualify through community solar options.',
    link: 'https://illinoissolarforall.com',
  },
  {
    name: 'Net Metering (ComEd)',
    type: 'net_metering',
    scope: 'utility',
    description:
      'When your solar panels make more power than you use, the excess goes to the grid and ComEd credits your account at the retail electricity rate. Credits roll over month-to-month.',
    estimatedValue: 'Retail rate credit (~$0.12–0.15/kWh) for excess energy sent to grid',
    eligibility: 'ComEd customers with grid-tied solar systems up to 2 MW.',
    link: 'https://www.comed.com/SiteCollectionDocuments/SmartEnergy/SolarAndRenewables/NetMetering.pdf',
  },
  {
    name: 'Net Metering (Ameren Illinois)',
    type: 'net_metering',
    scope: 'utility',
    description:
      'Same as ComEd net metering — excess solar sent to the grid earns credits at the retail rate on your Ameren bill. Credits apply to future bills.',
    estimatedValue: 'Retail rate credit for excess energy sent to grid',
    eligibility: 'Ameren Illinois customers with grid-tied solar systems.',
    link: 'https://www.ameren.com/illinois/home/products-and-services/renewable-energy/solar',
  },
  {
    name: 'Property Tax Exemption (Illinois)',
    type: 'exemption',
    scope: 'state',
    description:
      'Solar panels increase your home\'s value, but Illinois law says that added value is excluded from your property tax assessment for 4 years (renewable). You get the home value boost without the higher tax bill.',
    estimatedValue: 'Avoids property tax increase on ~$15,000–30,000 of added home value',
    eligibility:
      'Illinois homeowners who install solar on their primary residence. Must be an approved solar energy system. File with your county assessor after installation.',
    link: 'https://tax.illinois.gov/research/publications/administrative/pub-112.html',
  },
  {
    name: 'Sales Tax Exemption (Illinois)',
    type: 'exemption',
    scope: 'state',
    description:
      'Solar equipment purchases in Illinois are exempt from the 6.25% state sales tax. This applies to solar panels, inverters, and related equipment.',
    estimatedValue: '6.25% savings on equipment costs (~$500–2,000 on a typical system)',
    eligibility: 'Any Illinois resident purchasing qualified solar energy equipment.',
    link: 'https://www2.illinois.gov/rev/research/taxinformation/sales/Pages/RIT-12.aspx',
  },
];

// ─── Cook County IL ───────────────────────────────────────────────────────────

const COOK_COUNTY_INCENTIVES: Incentive[] = [
  {
    name: 'Elevate Energy Programs (Cook County)',
    type: 'program',
    scope: 'county',
    description:
      'Elevate Energy runs weatherization and energy efficiency programs for Cook County residents, often paired with solar. Getting weatherization done first makes your solar system more effective and may reduce its required size.',
    estimatedValue: 'Free weatherization services; value varies by home',
    eligibility:
      'Cook County residents at or below 80% AMI. Income-qualified households can combine this with ILSFA solar.',
    link: 'https://www.elevateenergy.org/programs',
  },
  {
    name: 'CEJA Community Solar (Cook County)',
    type: 'program',
    scope: 'county',
    description:
      'Through the Climate and Equitable Jobs Act (CEJA), renters and homeowners who can\'t install rooftop panels can subscribe to a community solar farm and receive credits on their electric bill.',
    estimatedValue: 'Typically 5–15% discount on subscribed electricity',
    eligibility:
      'ComEd or Ameren customers in Cook County. Income-qualified subscribers may receive larger discounts. No roof or ownership required.',
    link: 'https://illinoisshines.com/community-solar/',
  },
];

// ─── California ───────────────────────────────────────────────────────────────

const CA_INCENTIVES: Incentive[] = [
  {
    name: 'Self-Generation Incentive Program (SGIP)',
    type: 'rebate',
    scope: 'state',
    description:
      'California\'s battery storage rebate. Provides upfront dollars per watt-hour of battery capacity installed. Equity tiers give higher rebates to customers in disadvantaged communities or those who rely on medical equipment.',
    estimatedValue: '$0.15–$1.00/Wh depending on equity status (~$2,000–12,000 for a home battery)',
    eligibility:
      'California customers of PG&E, SCE, SoCalGas, or SDG&E. Equity applicants get priority and higher rebates.',
    link: 'https://www.selfgenca.com',
  },
  {
    name: 'Net Energy Metering (NEM 3.0)',
    type: 'net_metering',
    scope: 'state',
    description:
      'California\'s current net metering program credits solar exports at the "avoided cost" rate — lower than retail, but still meaningful. Adding battery storage is now more valuable in CA to shift solar use to peak hours.',
    estimatedValue: 'Avoided cost credits (~$0.05–0.08/kWh); value varies by time of export',
    eligibility: 'All California IOU customers (PG&E, SCE, SDG&E) with solar installed after April 2023.',
    link: 'https://www.cpuc.ca.gov/nem',
  },
  {
    name: 'Property Tax Exclusion (California)',
    type: 'exemption',
    scope: 'state',
    description:
      'Solar systems installed on California homes are excluded from property tax reassessment. Your home value goes up but your tax bill doesn\'t.',
    estimatedValue: 'Avoids property tax increase on solar-added home value',
    eligibility: 'California homeowners with new solar installations. No application needed — automatic.',
    link: 'https://www.boe.ca.gov/proptaxes/pdf/lta0402.pdf',
  },
];

// ─── New York ─────────────────────────────────────────────────────────────────

const NY_INCENTIVES: Incentive[] = [
  {
    name: 'NY-Sun Incentive',
    type: 'rebate',
    scope: 'state',
    description:
      'New York\'s main solar incentive — an upfront rebate paid per watt of solar capacity installed. The amount varies by utility territory (Con Ed, NYSEG, etc.) and decreases as more solar is installed in each region.',
    estimatedValue: '$0.20–$0.40/W installed (~$1,800–3,500 for a typical home)',
    eligibility:
      'NY homeowners using a participating installer. Must be in a NYSERDA-covered utility territory.',
    link: 'https://www.nyserda.ny.gov/ny-sun',
  },
  {
    name: '25% New York State Tax Credit',
    type: 'tax_credit',
    scope: 'state',
    description:
      'On top of the federal 30% credit, New York offers a 25% state income tax credit on solar system costs, capped at $5,000 per household.',
    estimatedValue: '25% of system cost, up to $5,000',
    eligibility:
      'New York State residents who owe NY state income taxes. Primary residence only. Credit is nonrefundable.',
    link: 'https://www.tax.ny.gov/pit/credits/solar_energy_credit.htm',
  },
  {
    name: 'Net Metering (New York)',
    type: 'net_metering',
    scope: 'state',
    description:
      'NY utilities must credit solar customers at the retail rate for excess power sent to the grid. Credits roll over and can be used to offset future bills.',
    estimatedValue: 'Retail rate credits for excess energy (~$0.18–0.25/kWh in NY)',
    eligibility: 'New York State residential customers with grid-tied solar.',
    link: 'https://www.nyserda.ny.gov/All-Programs/NY-Sun/Solar-for-Your-Home/Net-Metering',
  },
];

// ─── Texas ────────────────────────────────────────────────────────────────────

const TX_INCENTIVES: Incentive[] = [
  {
    name: 'No State Income Tax on Solar Savings',
    type: 'exemption',
    scope: 'state',
    description:
      'Texas has no state income tax, so the savings you get from solar (reduced electric bills) are completely tax-free at the state level. Your solar savings stay yours.',
    estimatedValue: 'Full savings kept — no state tax on reduced utility costs',
    eligibility: 'All Texas residents. No application needed.',
    link: 'https://comptroller.texas.gov',
  },
  {
    name: 'Property Tax Exemption (Texas)',
    type: 'exemption',
    scope: 'state',
    description:
      'Texas law exempts 100% of the added home value from solar installations from property taxes. Your home is worth more, but you\'re not taxed on that increase.',
    estimatedValue: '100% exemption on solar-added property value',
    eligibility: 'Texas homeowners with solar installed. File with your county appraisal district.',
    link: 'https://comptroller.texas.gov/taxes/property-tax/exemptions/solar.php',
  },
  {
    name: 'Austin Energy Solar Rebate',
    type: 'rebate',
    scope: 'utility',
    description:
      'Austin Energy customers can receive an upfront rebate when going solar, paid per watt installed. Combined with the federal tax credit, this significantly reduces the cost of going solar in Austin.',
    estimatedValue: 'Up to $2,500 for residential systems (check current rates)',
    eligibility: 'Austin Energy customers only. Must use an Austin Energy-approved installer.',
    link: 'https://austinenergy.com/green-power/solar',
  },
  {
    name: 'CPS Energy Solar Incentives (San Antonio)',
    type: 'rebate',
    scope: 'utility',
    description:
      'CPS Energy offers rebates and incentives for solar installations in San Antonio. Programs change — check directly for current offerings.',
    estimatedValue: 'Varies; typically $500–2,000 for residential systems',
    eligibility: 'CPS Energy customers in the San Antonio area.',
    link: 'https://www.cpsenergy.com/en/about-us/what-we-do/renewable-energy/solar.html',
  },
];

// ─── Michigan ─────────────────────────────────────────────────────────────────

const MI_INCENTIVES: Incentive[] = [
  {
    name: 'Net Metering (Michigan)',
    type: 'net_metering',
    scope: 'state',
    description:
      'Michigan utilities are required to offer net metering to solar customers. Excess electricity sent to the grid is credited at a rate set by the utility, typically at or near the retail rate.',
    estimatedValue: 'Credits at retail or near-retail rate for excess solar',
    eligibility: 'Michigan residents with solar connected to the grid through Consumers Energy or DTE Energy.',
    link: 'https://www.michigan.gov/mpsc/commission/cases/solar',
  },
  {
    name: 'PACE Financing (Michigan)',
    type: 'program',
    scope: 'county',
    description:
      'Property Assessed Clean Energy (PACE) financing lets you pay for solar through your property tax bill over time — no upfront cost and no traditional loan required. Available in participating Michigan counties.',
    estimatedValue: 'No upfront cost; typically 5–20 year repayment on property tax bill',
    eligibility:
      'Property owners in participating Michigan counties. Check with your county to see if PACE is available.',
    link: 'https://www.michigan.gov/egle/about/organization/materials-management/energy',
  },
];

// ─── Georgia ──────────────────────────────────────────────────────────────────

const GA_INCENTIVES: Incentive[] = [
  {
    name: 'Net Metering (Georgia Power)',
    type: 'net_metering',
    scope: 'utility',
    description:
      'Georgia Power offers net metering credits for excess solar sent to the grid, but at the avoided cost rate rather than retail — meaning credits are lower than your purchase rate. Still reduces your bill.',
    estimatedValue: 'Avoided cost rate credits (~$0.04–0.06/kWh)',
    eligibility: 'Georgia Power residential customers with solar systems up to 10 kW.',
    link: 'https://www.georgiapower.com/products-programs/renewable-energy/for-your-home/solar.html',
  },
  {
    name: 'Property Tax Exemption (Georgia)',
    type: 'exemption',
    scope: 'state',
    description:
      'Solar energy equipment and the added home value from solar installations are exempt from Georgia property taxes.',
    estimatedValue: 'Avoids property tax increase on solar-added home value',
    eligibility: 'Georgia homeowners with solar installed. May require filing with county tax assessor.',
    link: 'https://dor.georgia.gov/taxes/business-taxes/sales-use-tax/exemptions-and-exclusions',
  },
];

// ─── Ohio ─────────────────────────────────────────────────────────────────────

const OH_INCENTIVES: Incentive[] = [
  {
    name: 'Net Metering (Ohio)',
    type: 'net_metering',
    scope: 'state',
    description:
      'Ohio utilities must offer net metering to solar customers. Excess solar is credited at the retail rate and applied to your bill.',
    estimatedValue: 'Retail rate credits for excess solar energy',
    eligibility: 'Ohio residential solar customers with grid-tied systems up to 20 kW.',
    link: 'https://puco.ohio.gov/utilities/electricity/consumers/renewable-energy/',
  },
  {
    name: 'Property Tax Exemption (Ohio)',
    type: 'exemption',
    scope: 'state',
    description:
      'Solar installations on Ohio homes are exempt from property tax increases. The added value from your system won\'t raise your annual property tax bill.',
    estimatedValue: '100% exemption on solar-added property value',
    eligibility: 'Ohio homeowners with qualifying solar installations.',
    link: 'https://tax.ohio.gov/wps/portal/gov/tax/business/ohio-business-taxes/sales-and-use/information/st-2004-02',
  },
];

// ─── Florida ──────────────────────────────────────────────────────────────────

const FL_INCENTIVES: Incentive[] = [
  {
    name: 'Property Tax Exemption (Florida)',
    type: 'exemption',
    scope: 'state',
    description:
      'Florida provides a 100% property tax exemption on the added value of residential solar installations. Your home value goes up, but your tax bill doesn\'t.',
    estimatedValue: '100% exemption on solar-added property value',
    eligibility: 'Florida homeowners with solar installed on their primary or secondary residence.',
    link: 'https://floridarevenue.com/property/Pages/Taxpayers_Exemptions.aspx',
  },
  {
    name: 'Sales Tax Exemption (Florida)',
    type: 'exemption',
    scope: 'state',
    description:
      'Solar energy systems and components are exempt from Florida\'s 6% sales tax. This applies to panels, inverters, and other solar hardware.',
    estimatedValue: '6% savings on equipment costs',
    eligibility: 'Florida residents purchasing solar equipment.',
    link: 'https://floridarevenue.com/taxes/taxesfees/Pages/sales_tax.aspx',
  },
  {
    name: 'Net Metering (Florida)',
    type: 'net_metering',
    scope: 'state',
    description:
      'Florida utilities must offer net metering. Excess solar is credited at the retail rate on a monthly basis.',
    estimatedValue: 'Retail rate credits for excess solar energy',
    eligibility: 'Florida residents with grid-tied solar systems through a major utility.',
    link: 'https://www.floridapsc.com/Publications/Library/Brochures/solar_panel_brochure.pdf',
  },
];

// ─── Colorado ─────────────────────────────────────────────────────────────────

const CO_INCENTIVES: Incentive[] = [
  {
    name: 'Net Metering (Colorado)',
    type: 'net_metering',
    scope: 'state',
    description:
      'Colorado utilities must offer net metering at the retail rate. Credits for excess solar roll over month-to-month and can be used to offset future bills.',
    estimatedValue: 'Retail rate credits (~$0.10–0.15/kWh)',
    eligibility: 'Colorado residents with grid-tied solar through Xcel Energy or other participating utilities.',
    link: 'https://www.xcelenergy.com/programs_and_rebates/residential_programs_and_rebates/solar_rewards',
  },
  {
    name: 'Xcel Energy Solar Rewards Program',
    type: 'rebate',
    scope: 'utility',
    description:
      'Xcel Energy pays Colorado customers for solar RECs generated by their systems — a monthly payment per kWh on top of net metering. The program has waitlists but can significantly improve payback.',
    estimatedValue: '~$0.02–0.05/kWh monthly payments for 20 years',
    eligibility: 'Xcel Energy (Colorado) residential customers. Apply through an approved installer.',
    link: 'https://www.xcelenergy.com/programs_and_rebates/residential_programs_and_rebates/solar_rewards',
  },
];

// ─── New Jersey ───────────────────────────────────────────────────────────────

const NJ_INCENTIVES: Incentive[] = [
  {
    name: 'Successor Solar Incentive (SuSI)',
    type: 'program',
    scope: 'state',
    description:
      'New Jersey\'s solar incentive program — you earn Solar Renewable Energy Certificates (SRECs) that are sold quarterly through an administratively set price. Replaces the older SREC market.',
    estimatedValue: '~$90–120/SREC (1 SREC = 1 MWh generated), 15-year program',
    eligibility:
      'NJ residential and commercial solar customers. Must register system with NJ BPU after installation.',
    link: 'https://www.njcleanenergy.com/renewable-energy/programs/solar-successor-incentive-program-susi',
  },
  {
    name: 'Net Metering (New Jersey)',
    type: 'net_metering',
    scope: 'state',
    description:
      'NJ utilities must credit excess solar at the retail rate. Annual true-up means you don\'t lose unused credits at year end.',
    estimatedValue: 'Retail rate credits for excess solar energy',
    eligibility: 'New Jersey residents with grid-tied solar systems.',
    link: 'https://www.njcleanenergy.com/renewable-energy/homeowner/understand-your-solar-options/net-metering',
  },
  {
    name: 'Property Tax Exemption (New Jersey)',
    type: 'exemption',
    scope: 'state',
    description:
      'New Jersey exempts the added value of solar installations from property tax assessment. Solar can add significant home value without raising your tax bill.',
    estimatedValue: '100% exemption on solar-added property value',
    eligibility: 'NJ homeowners with qualifying solar installations.',
    link: 'https://www.njleg.state.nj.us/Bills/2002/S1500/1456_I1.HTM',
  },
];

// ─── Main Export Function ─────────────────────────────────────────────────────

const STATE_INCENTIVES: Record<string, Incentive[]> = {
  IL: IL_INCENTIVES,
  CA: CA_INCENTIVES,
  NY: NY_INCENTIVES,
  TX: TX_INCENTIVES,
  MI: MI_INCENTIVES,
  GA: GA_INCENTIVES,
  OH: OH_INCENTIVES,
  FL: FL_INCENTIVES,
  CO: CO_INCENTIVES,
  NJ: NJ_INCENTIVES,
};

const COUNTY_INCENTIVES: Record<string, Record<string, Incentive[]>> = {
  IL: {
    Cook: COOK_COUNTY_INCENTIVES,
  },
};

export function getIncentives(state: string, county?: string): Incentive[] {
  const stateIncentives = STATE_INCENTIVES[state] ?? [];
  const countyIncentives = county && COUNTY_INCENTIVES[state]?.[county]
    ? COUNTY_INCENTIVES[state][county]
    : [];
  return [...FEDERAL_INCENTIVES, ...stateIncentives, ...countyIncentives];
}

export const US_STATES: { code: string; name: string }[] = [
  { code: 'IL', name: 'Illinois' },
  { code: 'CA', name: 'California' },
  { code: 'NY', name: 'New York' },
  { code: 'TX', name: 'Texas' },
  { code: 'MI', name: 'Michigan' },
  { code: 'GA', name: 'Georgia' },
  { code: 'OH', name: 'Ohio' },
  { code: 'FL', name: 'Florida' },
  { code: 'CO', name: 'Colorado' },
  { code: 'NJ', name: 'New Jersey' },
  { code: 'OTHER', name: 'Other (Federal Only)' },
];
